_dataset_map = {
    "data": "data",
    "ZTT": "DY",
    "ZL": "DY",
    "ZJ": "DY",
    "ZTT_NLO": "DYNLO",
    "ZL_NLO": "DYNLO",
    "ZJ_NLO": "DYNLO",
    "TTT": "TT",
    "TTL": "TT",
    "TTJ": "TT",
    "TTVT": "TTV",
    "TTVL": "TTV",
    "TTVJ": "TTV",
    "VVT": "VV",
    "VVL": "VV",
    "VVJ": "VV",
    "VVVT": "VVV",
    "VVVL": "VVV",
    "VVVJ": "VVV",
    "STT": "ST",
    "STL": "ST",
    "STJ": "ST",
    "EMB": "EMB",
    "EWK": "EWK",
    "W": "W",
    "W_NLO": "WNLO",
    "qqH125": "qqH",
    "ggH125": "ggH",
    "ttH125": "ttH",
    "VH125": "VH",
    "ZH125": "ZH",
    "WH125": "WH",
}

_process_map = {
    "data": "data",
    "ZTT": "DY-ZTT",
    "ZL": "DY-ZL",
    "ZJ": "DY-ZJ",
    "ZTT_NLO": "DY_NLO-ZTT",
    "ZL_NLO": "DY_NLO-ZL",
    "ZJ_NLO": "DY_NLO-ZJ",
    "TTT": "TT-TTT",
    "TTL": "TT-TTL",
    "TTJ": "TT-TTJ",
    "TTVT": "TTV-TTVT",
    "TTVL": "TTV-TTVL",
    "TTVJ": "TTV-TTVJ",
    "VVT": "VV-VVT",
    "VVL": "VV-VVL",
    "VVJ": "VV-VVJ",
    "VVVT": "VVV-VVVT",
    "VVVL": "VVV-VVVL",
    "VVVJ": "VVV-VVVJ",
    "STT": "ST-STT",
    "STL": "ST-STL",
    "STJ": "ST-STJ",
    "EMB": "Embedded",
    "EWK": "EWK",
    "W": "W",
    "W_NLO": "W",
    "qqH125": "qqH125",
    "ggH125": "ggH125",
    "ttH125": "ttH125",
    "VH125": "VH125",
    "ZH125": "ZH125",
    "WH125": "WH125",
}

_name_string = "{dataset}#{channel}{process}{selection}#{variation}#{variable}"
