#!/bin/bash
set -e
NTUPLETAG=$1
ERA=$2

KINGMAKER_BASEDIR_PATH="/store/user/${USER}/CROWN/ntuples/${NTUPLETAG}/CROWNRun/"
KINGMAKER_BASEDIR_XROOTD="root://cmsdcache-kit-disk.gridka.de/"
XSEC_FRIENDS_PATH="/store/user/${USER}/CROWN/ntuples/${NTUPLETAG}/CROWNFriends/xsec/"

# KINGMAKER_BASEDIR="/ceph/${USER}/CROWN/ntuples/${NTUPLETAG}/CROWNRun/"
# KINGMAKER_BASEDIR_XROOTD="${KINGMAKER_BASEDIR}"
# XSEC_FRIENDS="/ceph/${USER}/CROWN/ntuples/${NTUPLETAG}/CROWNFriends/xsec/"

KINGMAKER_BASEDIR="${KINGMAKER_BASEDIR_XROOTD}${KINGMAKER_BASEDIR_PATH}"
XSEC_FRIENDS="${KINGMAKER_BASEDIR_XROOTD}${XSEC_FRIENDS_PATH}"



if [[ $ERA == *"2016"* ]]; then
    NTUPLES=$KINGMAKER_BASEDIR
elif [[ $ERA == *"2017"* ]]; then
    NTUPLES=$KINGMAKER_BASEDIR
elif [[ $ERA == *"2018"* ]]; then
    NTUPLES=$KINGMAKER_BASEDIR
fi