from ntuple_processor import Histogram
import numpy as np

common_binning = {
    "genbosonpt": Histogram("genbosonpt", "genbosonpt", np.arange(0, 150, 10)),
    "deltaR_ditaupair": Histogram("deltaR_ditaupair", "deltaR_ditaupair", np.arange(0, 5, 0.2)),
    "mTdileptonMET_puppi": Histogram("mTdileptonMET_puppi", "mTdileptonMET_puppi", np.arange(0, 200, 4)),
    "pzetamissvis": Histogram("pzetamissvis", "pzetamissvis", np.arange(-200, 200, 10)),
    "pzetamissvis_pf": Histogram("pzetamissvis_pf", "pzetamissvis_pf", np.arange(-200, 200, 5)),
    "m_sv_puppi": Histogram("m_sv_puppi", "m_sv_puppi", np.arange(0, 225, 5)),
    "pt_sv_puppi": Histogram("pt_sv_puppi", "pt_sv_puppi", np.arange(0, 160, 5)),
    "eta_sv_puppi": Histogram("eta_sv_puppi", "eta_sv_puppi", np.linspace(-2.5, 2.5, 50)),
    "m_vis": Histogram("m_vis", "m_vis", np.arange(0, 280, 10)),
    "ME_q2v1": Histogram("ME_q2v1", "ME_q2v1", np.arange(0, 300000, 6000)),
    "ME_q2v2": Histogram("ME_q2v1", "ME_q2v1", np.arange(0, 300000, 6000)),
    "ME_costheta1": Histogram("ME_costheta1", "ME_costheta1", np.linspace(-1, 1, 50)),
    "ME_costheta2": Histogram("ME_costheta2", "ME_costheta2", np.linspace(-1, 1, 50)),
    "ME_costhetastar": Histogram("ME_costhetastar", "ME_costhetastar", np.linspace(-1, 1, 50)),
    "ME_phi": Histogram("ME_phi", "ME_phi", np.linspace(-3.14, 3.14, 50)),
    "ME_phi1": Histogram("ME_phi1", "ME_phi1", np.linspace(-3.14, 3.14, 50)),
    "pfmetphi": Histogram("pfmetphi", "pfmetphi", np.linspace(-3.14, 3.14, 20)),
    "metphi": Histogram("metphi", "metphi", np.linspace(-3.14, 3.14, 20)),
    "mt_tot": Histogram("mt_tot", "mt_tot", np.arange(0, 400, 10)),
    "mt_tot_puppi": Histogram("mt_tot_puppi", "mt_tot_puppi", np.arange(0, 400, 10)),
    "pt_1": Histogram("pt_1", "pt_1", np.append(np.array([0]) ,np.arange(20, 160, 5))),
    "pt_2": Histogram("pt_2", "pt_2", np.append(np.array([0]) ,np.arange(20, 140, 5))),
    "eta_1": Histogram("eta_1", "eta_1", np.linspace(-2.5, 2.5, 20)),
    "eta_2": Histogram("eta_2", "eta_2", np.linspace(-2.5, 2.5, 20)),
    "phi_1": Histogram("phi_1", "phi_1", np.linspace(-3.14, 3.14, 20)),
    "phi_2": Histogram("phi_2", "phi_2", np.linspace(-3.14, 3.14, 20)),
    "jpt_1": Histogram("jpt_1", "jpt_1", np.append(np.array([0]) ,np.arange(20, 360, 10))),
    "jpt_2": Histogram("jpt_2", "jpt_2", np.append(np.array([0]) ,np.arange(20, 180, 10))),
    "jeta_1": Histogram("jeta_1", "jeta_1", np.linspace(-5, 5, 30)),
    "jeta_2": Histogram("jeta_2", "jeta_2", np.linspace(-5, 5, 30)),
    "jphi_1": Histogram("jphi_1", "jphi_1", np.linspace(-3.14, 3.14, 20)),
    "jphi_2": Histogram("jphi_2", "jphi_2", np.linspace(-3.14, 3.14, 20)),
    "jdeta": Histogram("jdeta", "jdeta", np.arange(0, 6, 0.2)),
    "njets": Histogram("njets", "njets", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]),
    "nbtag": Histogram("nbtag", "nbtag", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5]),
    "njets_boosted": Histogram("njets_boosted", "njets_boosted", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]),
    "nbtag_boosted": Histogram("nbtag_boosted", "nbtag_boosted", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5]),
    "tau_decaymode_1": Histogram(
            "tau_decaymode_1",
            "tau_decaymode_1",
            [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5],
        ),
    "tau_decaymode_2": Histogram(
        "tau_decaymode_2",
        "tau_decaymode_2",
        [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5],
    ),
    "jet_hemisphere": Histogram("jet_hemisphere", "jet_hemisphere", [-0.5, 0.5, 1.5]),
    "rho": Histogram("rho", "rho", np.arange(0, 100, 2)),
    "mass_1": Histogram("mass_1", "mass_1", np.arange(0, 2, 0.1)),
    "mass_2": Histogram("mass_2", "mass_2", np.arange(0, 2, 0.1)),
    "mt_1": Histogram("mt_1", "mt_1", np.arange(0, 220, 10)),
    "mt_2": Histogram("mt_2", "mt_2", np.arange(0, 220, 10)),
    "mt_1_pf": Histogram("mt_1_pf", "mt_1_pf", np.arange(0, 220, 10)),
    "mt_2_pf": Histogram("mt_2_pf", "mt_2_pf", np.arange(0, 220, 10)),
    "pt_vis": Histogram("pt_vis", "pt_vis", np.arange(0, 160, 5)),
    "pt_tt": Histogram("pt_tt", "pt_tt", np.arange(0, 160, 5)),
    "pt_dijet": Histogram("pt_dijet", "pt_dijet", np.arange(0, 300, 10)),
    "pt_tt_pf": Histogram("pt_tt_pf", "pt_tt_pf", np.arange(0, 160, 5)),
    "pt_ttjj": Histogram("pt_ttjj", "pt_ttjj", np.arange(0, 160, 5)),
    "mjj": Histogram("mjj", "mjj", np.arange(0, 380, 20)),
    "met": Histogram("met", "met", np.arange(0, 500, 30)),
    "pfmet": Histogram("pfmet", "pfmet", np.arange(0, 250, 10)),
    "iso_1": Histogram("iso_1", "iso_1", np.linspace(0, 0.3, 50)),
    "iso_2": Histogram("iso_2", "iso_2", np.linspace(0, 1.0, 50)),
    # kinfit
    "kinfit_mX": Histogram("kinfit_mX", "kinfit_mX", np.arange(100, 905, 20)),
    "kinfit_mY": Histogram("kinfit_mY", "kinfit_mY",  np.arange(15, 530, 30)), #[0,7.5,12.5,17.5,22.5,27.5,32.5,37.5,42.5,47.5,52.5,57.5,62.5,67.5,72.5,77.5,82.5,87.5,92.5,97.5,105.,115.,122.5,127.5,135.,145.,165.,195.,225.,255.,285.,315.,345.,375.,405.,435.,465.,495.,525.]),
    "kinfit_chi2": Histogram("kinfit_chi2", "kinfit_chi2", np.arange(0, 50, 1)),
    "kinfit_convergence": Histogram("kinfit_convergence", "kinfit_convergence", [-4.5,-3.5,-2.5,-1.5,-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]),
    "kinfit_mX_YToBB": Histogram("kinfit_mX_YToBB", "kinfit_mX_YToBB", np.arange(100, 905, 20)),
    "kinfit_mY_YToBB": Histogram("kinfit_mY_YToBB", "kinfit_mY_YToBB",  np.arange(15, 530, 30)),
    "kinfit_chi2_YToBB": Histogram("kinfit_chi2_YToBB", "kinfit_chi2_YToBB", np.arange(0, 50, 1)),
    "kinfit_convergence_YToBB": Histogram("kinfit_convergence_YToBB", "kinfit_convergence_YToBB", [-4.5,-3.5,-2.5,-1.5,-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]),
    "kinfit_mX_YToTauTau": Histogram("kinfit_mX_YToTauTau", "kinfit_mX_YToTauTau", np.arange(100, 905, 20)),
    "kinfit_mY_YToTauTau": Histogram("kinfit_mY_YToTauTau", "kinfit_mY_YToTauTau",  np.arange(15, 530, 30)),
    "kinfit_chi2_YToTauTau": Histogram("kinfit_chi2_YToTauTau", "kinfit_chi2_YToTauTau", np.arange(0, 50, 1)),
    "kinfit_convergence_YToTauTau": Histogram("kinfit_convergence_YToTauTau", "kinfit_convergence_YToTauTau", [-4.5,-3.5,-2.5,-1.5,-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]),
    "kinfit_mX_boosted": Histogram("kinfit_mX_boosted", "kinfit_mX_boosted", np.arange(100, 905, 20)),
    "kinfit_mY_boosted": Histogram("kinfit_mY_boosted", "kinfit_mY_boosted",  np.arange(15, 530, 30)), #[0,7.5,12.5,17.5,22.5,27.5,32.5,37.5,42.5,47.5,52.5,57.5,62.5,67.5,72.5,77.5,82.5,87.5,92.5,97.5,105.,115.,122.5,127.5,135.,145.,165.,195.,225.,255.,285.,315.,345.,375.,405.,435.,465.,495.,525.]),
    "kinfit_chi2_boosted": Histogram("kinfit_chi2_boosted", "kinfit_chi2_boosted", np.arange(0, 50, 1)),
    "kinfit_convergence_boosted": Histogram("kinfit_convergence_boosted", "kinfit_convergence_boosted", [-4.5,-3.5,-2.5,-1.5,-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]),
    "kinfit_mX_YToBB_boosted": Histogram("kinfit_mX_YToBB_boosted", "kinfit_mX_YToBB_boosted", np.arange(100, 905, 20)),
    "kinfit_mY_YToBB_boosted": Histogram("kinfit_mY_YToBB_boosted", "kinfit_mY_YToBB_boosted",  np.arange(15, 530, 30)),
    "kinfit_chi2_YToBB_boosted": Histogram("kinfit_chi2_YToBB_boosted", "kinfit_chi2_YToBB_boosted", np.arange(0, 50, 1)),
    "kinfit_mX_YToTauTau_boosted": Histogram("kinfit_mX_YToTauTau_boosted", "kinfit_mX_YToTauTau_boosted", np.arange(100, 905, 20)),
    "kinfit_mY_YToTauTau_boosted": Histogram("kinfit_mY_YToTauTau_boosted", "kinfit_mY_YToTauTau_boosted",  np.arange(15, 530, 30)),
    "kinfit_chi2_YToTauTau_boosted": Histogram("kinfit_chi2_YToTauTau_boosted", "kinfit_chi2_YToTauTau_boosted", np.arange(0, 50, 1)),
    # fastmtt variables
    "m_fastmtt": Histogram("m_fastmtt", "m_fastmtt", np.arange(0, 405, 10)),
    "pt_fastmtt": Histogram("pt_fastmtt", "pt_fastmtt", np.arange(0, 305, 10)),
    "eta_fastmtt": Histogram("eta_fastmtt", "eta_fastmtt", np.linspace(-2.5, 2.5, 30)),
    "phi_fastmtt": Histogram("phi_fastmtt", "phi_fastmtt", np.linspace(-3.14, 3.14, 30)),
    "npartons": Histogram("npartons", "npartons", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]),
    "pt_tautaubb": Histogram("pt_tautaubb", "pt_tautaubb", np.arange(0, 510, 20)),
    "mass_tautaubb": Histogram("mass_tautaubb", "mass_tautaubb", np.arange(100, 905, 20)),
    # b jets
    "bpt_1": Histogram("bpt_1", "bpt_1", np.arange(0, 250, 5)),
    "bpt_2": Histogram("bpt_2", "bpt_2", np.arange(0, 250, 5)),
    "beta_1": Histogram("beta_1", "beta_1", np.linspace(-5, 5, 20)),
    "beta_2": Histogram("beta_2", "beta_2", np.linspace(-5, 5, 20)),
    "bphi_1": Histogram("bphi_1", "bphi_1", np.linspace(-3.14, 3.14, 30)),
    "bphi_2": Histogram("bphi_2", "bphi_2", np.linspace(-3.14, 3.14, 30)),
    "btag_value_1": Histogram("btag_value_1", "btag_value_1", np.linspace(0.2, 1.0, 40)),
    "btag_value_2": Histogram("btag_value_2", "btag_value_2", np.linspace(0.2, 1.0, 40)),
    "bpair_pt_1": Histogram("bpair_pt_1", "bpair_pt_1", np.arange(0, 260, 10)),
    "bpair_pt_2": Histogram("bpair_pt_2", "bpair_pt_2", np.arange(0, 180, 10)),
    "bpair_eta_1": Histogram("bpair_eta_1", "bpair_eta_1", np.linspace(-3, 3, 15)),
    "bpair_eta_2": Histogram("bpair_eta_2", "bpair_eta_2", np.linspace(-3, 3, 15)),
    "bpair_phi_1": Histogram("bpair_phi_1", "bpair_phi_1", np.linspace(-3.14, 3.14, 15)),
    "bpair_phi_2": Histogram("bpair_phi_2", "bpair_phi_2", np.linspace(-3.14, 3.14, 15)),
    "bpair_btag_value_1": Histogram("bpair_btag_value_1", "bpair_btag_value_1", np.linspace(0.2, 1.0, 15)),
    "bpair_btag_value_2": Histogram("bpair_btag_value_2", "bpair_btag_value_2", np.linspace(0.0, 1.0, 20)),
    "bpair_m_inv": Histogram("bpair_m_inv", "bpair_m_inv", np.arange(0, 425, 20)),
    "bpair_pt_dijet": Histogram("bpair_pt_dijet", "bpair_pt_dijet", np.arange(0, 300, 20)),
    "bpair_deltaR": Histogram("bpair_deltaR", "bpair_deltaR", np.arange(0, 5, 0.4)),
    "bpair_pt_1_boosted": Histogram("bpair_pt_1_boosted", "bpair_pt_1_boosted", np.arange(0, 260, 10)),
    "bpair_pt_2_boosted": Histogram("bpair_pt_2_boosted", "bpair_pt_2_boosted", np.arange(0, 180, 10)),
    "bpair_eta_1_boosted": Histogram("bpair_eta_1_boosted", "bpair_eta_1_boosted", np.linspace(-3, 3, 15)),
    "bpair_eta_2_boosted": Histogram("bpair_eta_2_boosted", "bpair_eta_2_boosted", np.linspace(-3, 3, 15)),
    "bpair_phi_1_boosted": Histogram("bpair_phi_1_boosted", "bpair_phi_1_boosted", np.linspace(-3.14, 3.14, 15)),
    "bpair_phi_2_boosted": Histogram("bpair_phi_2_boosted", "bpair_phi_2_boosted", np.linspace(-3.14, 3.14, 15)),
    "bpair_btag_value_1_boosted": Histogram("bpair_btag_value_1_boosted", "bpair_btag_value_1_boosted", np.linspace(0.2, 1.0, 15)),
    "bpair_btag_value_2_boosted": Histogram("bpair_btag_value_2_boosted", "bpair_btag_value_2_boosted", np.linspace(0.0, 1.0, 20)),
    "bpair_m_inv_boosted": Histogram("bpair_m_inv_boosted", "bpair_m_inv_boosted", np.arange(0, 425, 20)),
    "bpair_pt_dijet_boosted": Histogram("bpair_pt_dijet_boosted", "bpair_pt_dijet_boosted", np.arange(0, 300, 20)),
    "bpair_deltaR_boosted": Histogram("bpair_deltaR_boosted", "bpair_deltaR_boosted", np.arange(0, 5, 0.4)),
    # AK8 jets
    "fj_pt_1": Histogram("fj_pt_1", "fj_pt_1", np.arange(150, 650, 20)),
    "fj_eta_1": Histogram("fj_eta_1", "fj_eta_1", np.linspace(-5, 5, 20)),
    "fj_phi_1": Histogram("fj_phi_1", "fj_phi_1", np.linspace(-3.14, 3.14, 50)),
    "fj_mass_1": Histogram("fj_mass_1", "fj_mass_1", np.arange(0, 190, 5)),
    "fj_nsubjettiness_2over1_1": Histogram("fj_nsubjettiness_2over1_1", "fj_nsubjettiness_2over1_1", np.linspace(0, 1, 40)),
    "fj_nsubjettiness_3over2_1": Histogram("fj_nsubjettiness_3over2_1", "fj_nsubjettiness_3over2_1", np.linspace(0, 1, 40)),
    "fj_particleNet_XbbvsQCD_1": Histogram("fj_particleNet_XbbvsQCD_1", "fj_particleNet_XbbvsQCD_1", np.linspace(0, 1, 20)),
    "fj_msoftdrop_1": Histogram("fj_msoftdrop_1", "fj_msoftdrop_1", np.arange(0, 190, 5)),
    "fj_Xbb_pt": Histogram("fj_Xbb_pt", "fj_Xbb_pt", np.arange(140, 650, 20)),
    "fj_Xbb_eta": Histogram("fj_Xbb_eta", "fj_Xbb_eta", np.linspace(-3, 3, 20)),
    "fj_Xbb_phi": Histogram("fj_Xbb_phi", "fj_Xbb_phi", np.linspace(-3.14, 3.14, 20)),
    "fj_Xbb_mass": Histogram("fj_Xbb_mass", "fj_Xbb_mass", np.arange(0, 280, 10)),
    "fj_Xbb_nsubjettiness_2over1": Histogram("fj_Xbb_nsubjettiness_2over1", "fj_Xbb_nsubjettiness_2over1", np.linspace(0, 1, 20)),
    "fj_Xbb_nsubjettiness_3over2": Histogram("fj_Xbb_nsubjettiness_3over2", "fj_Xbb_nsubjettiness_3over2", np.linspace(0, 1, 20)),
    "fj_Xbb_particleNet_XbbvsQCD": Histogram("fj_Xbb_particleNet_XbbvsQCD", "fj_Xbb_particleNet_XbbvsQCD", np.linspace(0, 1, 20)),
    "fj_Xbb_msoftdrop": Histogram("fj_Xbb_msoftdrop", "fj_Xbb_msoftdrop", np.arange(0, 280, 10)),
    "nfatjets": Histogram("nfatjets", "nfatjets", [-0.5, 0.5, 1.5, 2.5, 3.5]),
    "mass_Xbb_mtt": Histogram("mass_Xbb_mtt", "ROOT::VecOps::RVec<float> pt{fj_Xbb_pt, pt_fastmtt}; ROOT::VecOps::RVec<float> eta{fj_Xbb_eta, eta_fastmtt}; ROOT::VecOps::RVec<float> phi{fj_Xbb_phi, phi_fastmtt}; ROOT::VecOps::RVec<float> mass{fj_Xbb_mass, m_fastmtt}; float minv = ROOT::VecOps::InvariantMass(pt, eta, phi, mass); return minv;", np.arange(0, 1450, 50)),
    "mass_Xbb_mtt_boosted": Histogram("mass_Xbb_mtt_boosted", "ROOT::VecOps::RVec<float> pt{fj_Xbb_pt_boosted, boosted_pt_fastmtt}; ROOT::VecOps::RVec<float> eta{fj_Xbb_eta_boosted, boosted_eta_fastmtt}; ROOT::VecOps::RVec<float> phi{fj_Xbb_phi_boosted, boosted_phi_fastmtt}; ROOT::VecOps::RVec<float> mass{fj_Xbb_mass_boosted, boosted_m_fastmtt}; float minv = ROOT::VecOps::InvariantMass(pt, eta, phi, mass); return minv;", np.arange(0, 1450, 50)),
    # boosted tau variables
    "boosted_pt_1": Histogram("boosted_pt_1", "boosted_pt_1", np.arange(20, 200, 10)),
    "boosted_pt_2": Histogram("boosted_pt_2", "boosted_pt_2", np.arange(20, 190, 10)),
    "boosted_eta_1": Histogram("boosted_eta_1", "boosted_eta_1", np.linspace(-2.5, 2.5, 15)),
    "boosted_eta_2": Histogram("boosted_eta_2", "boosted_eta_2", np.linspace(-2.5, 2.5, 15)),
    "boosted_phi_1": Histogram("boosted_phi_1", "boosted_phi_1", np.linspace(-3.14, 3.14, 15)),
    "boosted_phi_2": Histogram("boosted_phi_2", "boosted_phi_2", np.linspace(-3.14, 3.14, 15)),
    "boosted_mass_2": Histogram("boosted_mass_2", "boosted_mass_2", np.arange(0, 2.2, 0.1)),
    "boosted_iso_1": Histogram("boosted_iso_1", "boosted_iso_1", np.linspace(0, 0.4, 20)),
    "boosted_iso_2": Histogram("boosted_iso_2", "boosted_iso_2", np.linspace(0, 1.0, 20)),
    "boosted_mt_1": Histogram("boosted_mt_1", "boosted_mt_1", np.arange(0, 200, 10)),
    "boosted_mt_2": Histogram("boosted_mt_2", "boosted_mt_2", np.arange(0, 200, 10)),
    "boosted_tau_decaymode_2": Histogram(
        "boosted_tau_decaymode_2",
        "boosted_tau_decaymode_2",
        [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5],
    ),
    "boosted_deltaR_ditaupair": Histogram("boosted_deltaR_ditaupair", "boosted_deltaR_ditaupair", np.arange(0, 1., 0.1)),
    "boosted_m_vis": Histogram("boosted_m_vis", "boosted_m_vis", np.arange(0, 165, 10)),
    "boosted_pt_vis": Histogram("boosted_pt_vis", "boosted_pt_vis", np.arange(80, 290, 10)),
    "nboostedtaus": Histogram("nboostedtaus", "nboostedtaus", [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]),
    "boosted_m_fastmtt": Histogram("boosted_m_fastmtt", "boosted_m_fastmtt", np.arange(0, 300, 10)),
    "boosted_pt_fastmtt": Histogram("boosted_pt_fastmtt", "boosted_pt_fastmtt", np.arange(100, 300, 10)),
    "boosted_eta_fastmtt": Histogram("boosted_eta_fastmtt", "boosted_eta_fastmtt", np.linspace(-2.5, 2.5, 15)),
    "boosted_phi_fastmtt": Histogram("boosted_phi_fastmtt", "boosted_phi_fastmtt", np.linspace(-3.14, 3.14, 15)),
    "met_boosted": Histogram("met_boosted", "met_boosted", np.arange(0, 250, 10)),
    "metphi_boosted": Histogram("metphi_boosted", "metphi_boosted", np.linspace(-3.14, 3.14, 15)),
    "boosted_pt_tautaubb": Histogram("boosted_pt_tautaubb", "boosted_pt_tautaubb", np.arange(0, 510, 20)),
    "boosted_mass_tautaubb": Histogram("boosted_mass_tautaubb", "boosted_mass_tautaubb", np.arange(150, 2310, 30)),
    "fj_Xbb_pt_boosted": Histogram("fj_Xbb_pt_boosted", "fj_Xbb_pt_boosted", np.arange(140, 650, 20)),
    "fj_Xbb_eta_boosted": Histogram("fj_Xbb_eta_boosted", "fj_Xbb_eta_boosted", np.linspace(-3, 3, 20)),
    "fj_Xbb_phi_boosted": Histogram("fj_Xbb_phi_boosted", "fj_Xbb_phi_boosted", np.linspace(-3.14, 3.14, 20)),
    "fj_Xbb_mass_boosted": Histogram("fj_Xbb_mass_boosted", "fj_Xbb_mass_boosted", np.arange(0, 280, 10)),
    "fj_Xbb_nsubjettiness_2over1_boosted": Histogram("fj_Xbb_nsubjettiness_2over1_boosted", "fj_Xbb_nsubjettiness_2over1_boosted", np.linspace(0, 1, 20)),
    "fj_Xbb_nsubjettiness_3over2_boosted": Histogram("fj_Xbb_nsubjettiness_3over2_boosted", "fj_Xbb_nsubjettiness_3over2_boosted", np.linspace(0, 1, 20)),
    "fj_Xbb_particleNet_XbbvsQCD_boosted": Histogram("fj_Xbb_particleNet_XbbvsQCD_boosted", "fj_Xbb_particleNet_XbbvsQCD_boosted", np.linspace(0, 1, 20)),
    "fj_Xbb_msoftdrop_boosted": Histogram("fj_Xbb_msoftdrop_boosted", "fj_Xbb_msoftdrop_boosted", np.arange(0, 280, 10)),
    "nfatjets_boosted": Histogram("nfatjets_boosted", "nfatjets_boosted", [-0.5, 0.5, 1.5, 2.5, 3.5]),
    "deltaR_Z_fatjet": Histogram("deltaR_Z_fatjet", "ROOT::VecOps::DeltaR(eta_fastmtt, fj_Xbb_eta, phi_fastmtt, fj_Xbb_phi)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_jet1_fatjet": Histogram("deltaR_jet1_fatjet", "ROOT::VecOps::DeltaR(jeta_1, fj_Xbb_eta, jphi_1, fj_Xbb_phi)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau1_fatjet": Histogram("deltaR_tau1_fatjet", "ROOT::VecOps::DeltaR(eta_1, fj_Xbb_eta, phi_1, fj_Xbb_phi)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau2_fatjet": Histogram("deltaR_tau2_fatjet", "ROOT::VecOps::DeltaR(eta_2, fj_Xbb_eta, phi_2, fj_Xbb_phi)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau1_jet1": Histogram("deltaR_tau1_jet1", "ROOT::VecOps::DeltaR(eta_1, jeta_1, phi_1, jphi_1)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau2_jet1": Histogram("deltaR_tau2_jet1", "ROOT::VecOps::DeltaR(eta_2, jeta_1, phi_2, jphi_1)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau1_jet2": Histogram("deltaR_tau1_jet2", "ROOT::VecOps::DeltaR(eta_1, jeta_2, phi_1, jphi_2)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_tau2_jet2": Histogram("deltaR_tau2_jet2", "ROOT::VecOps::DeltaR(eta_2, jeta_2, phi_2, jphi_2)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_jet2_fatjet": Histogram("deltaR_jet2_fatjet", "ROOT::VecOps::DeltaR(jeta_2, fj_Xbb_eta, jphi_2, fj_Xbb_phi)*1", np.arange(0, 4.5, 0.1)),
    "deltaR_jet1_jet2": Histogram("deltaR_jet1_jet2", "ROOT::VecOps::DeltaR(jeta_1, jeta_2, jphi_1, jphi_2)*1", np.arange(0, 4.5, 0.1)),
    "balance_pT_fatjet_Z": Histogram("balance_pT_fatjet_Z", "(fj_Xbb_pt-met-pt_1-pt_2)/(fj_Xbb_pt+met+pt_1+pt_2)", np.arange(-0.5, 0.5, 0.02)),
    "cos_deltaPhi_met_tau1": Histogram("cos_deltaPhi_met_tau1", "cos(ROOT::VecOps::DeltaPhi(metphi, phi_1)*1)", np.arange(-1.5, 1.5, 0.1)),
    "deltaPhi_met_tau1": Histogram("deltaPhi_met_tau1", "ROOT::VecOps::DeltaPhi(metphi, phi_1)*1", np.arange(-3.5, 3.5, 0.2)),
    "sqrt_pt1_met": Histogram("sqrt_pt1_met", "sqrt(pt_1*met)", np.arange(0, 250, 20)),
    "cos_deltaPhi_met_tau2": Histogram("cos_deltaPhi_met_tau2", "cos(ROOT::VecOps::DeltaPhi(metphi, phi_2)*1)", np.arange(-1.5, 1.5, 0.1)),
    "deltaPhi_met_tau2": Histogram("deltaPhi_met_tau2", "ROOT::VecOps::DeltaPhi(metphi, phi_2)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaPhi_met_fatjet": Histogram("deltaPhi_met_fatjet", "ROOT::VecOps::DeltaPhi(metphi, fj_Xbb_phi)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaPhi_met_jet1": Histogram("deltaPhi_met_jet1", "ROOT::VecOps::DeltaPhi(metphi, jphi_1)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaPhi_jet1_fatjet": Histogram("deltaPhi_jet1_fatjet", "ROOT::VecOps::DeltaPhi(jphi_1, fj_Xbb_phi)*1", np.arange(-3.5, 3.5, 0.2)),
    "sqrt_pt2_met": Histogram("sqrt_pt2_met", "sqrt(pt_2*met)", np.arange(0, 250, 20)),
    "deltaPhi_tau1_tau2": Histogram("deltaPhi_tau1_tau2", "ROOT::VecOps::DeltaPhi(phi_1, phi_2)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaEta_tau1_tau2": Histogram("deltaEta_tau1_tau2", "abs(eta_1-eta_2)", np.arange(0, 5.0, 0.2)),
    "deltaPhi_jet1_jet2": Histogram("deltaPhi_jet1_jet2", "ROOT::VecOps::DeltaPhi(jphi_1, jphi_2)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaEta_jet1_jet2": Histogram("deltaEta_jet1_jet2", "abs(jeta_1-jeta_2)", np.arange(0, 5.0, 0.2)),
    "deltaPT_jet1_jet2": Histogram("deltaPT_jet1_jet2", "abs(jpt_1-jpt_2)", np.arange(0, 360, 15)),
    "deltaPhi_tau1_jet1": Histogram("deltaPhi_tau1_jet1", "ROOT::VecOps::DeltaPhi(phi_1, jphi_1)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaEta_tau1_jet1": Histogram("deltaEta_tau1_jet1", "abs(eta_1-jeta_1)", np.arange(0, 5.0, 0.2)),
    "deltaPhi_tau1_fatjet": Histogram("deltaPhi_tau1_fatjet", "ROOT::VecOps::DeltaPhi(phi_1, fj_Xbb_phi)*1", np.arange(-3.5, 3.5, 0.2)),
    "deltaEta_tau1_fatjet": Histogram("deltaEta_tau1_fatjet", "abs(eta_1-fj_Xbb_eta)", np.arange(0, 5.0, 0.2)),

    "deltaR_b1_mu": Histogram("deltaR_b1_mu", "ROOT::VecOps::DeltaR(bpair_eta_1_boosted, boosted_eta_1, bpair_phi_1_boosted, boosted_phi_1)*1", np.arange(0, 3.5, 0.05)),
    "deltaR_b2_tau": Histogram("deltaR_b2_tau", "ROOT::VecOps::DeltaR(bpair_eta_2_boosted, boosted_eta_2, bpair_phi_2_boosted, boosted_phi_2)*1", np.arange(0, 3.5, 0.05)),
    "deltaR_b2_mu": Histogram("deltaR_b2_mu", "ROOT::VecOps::DeltaR(bpair_eta_2_boosted, boosted_eta_1, bpair_phi_2_boosted, boosted_phi_1)*1", np.arange(0, 3.5, 0.05)),
    "deltaR_b1_tau": Histogram("deltaR_b1_tau", "ROOT::VecOps::DeltaR(bpair_eta_1_boosted, boosted_eta_2, bpair_phi_1_boosted, boosted_phi_2)*1", np.arange(0, 3.5, 0.05)),
    "deltaR_b1_addtau": Histogram("deltaR_b1_addtau", "ROOT::VecOps::DeltaR(bpair_eta_1_boosted, boosted_eta_add, bpair_phi_1_boosted, boosted_phi_add)*1", np.arange(0, 0.5, 0.01)),
    "deltaR_b2_addtau": Histogram("deltaR_b2_addtau", "ROOT::VecOps::DeltaR(bpair_eta_2_boosted, boosted_eta_add, bpair_phi_2_boosted, boosted_phi_add)*1", np.arange(0, 0.5, 0.01)),
    "deltaR_mu_addtau": Histogram("deltaR_mu_addtau", "ROOT::VecOps::DeltaR(boosted_eta_1, boosted_eta_add, boosted_phi_1, boosted_phi_add)*1", np.arange(0, 0.5, 0.01)),
    "deltaR_tau_addtau": Histogram("deltaR_tau_addtau", "ROOT::VecOps::DeltaR(boosted_eta_2, boosted_eta_add, boosted_phi_2, boosted_phi_add)*1", np.arange(0, 0.5, 0.01)),
    "deltaPT_tau_addtau": Histogram("deltaPT_tau_addtau", "abs(boosted_pt_2-boosted_pt_add)", np.arange(0, 20, 0.5)),
    "deltaPT_mu_addtau": Histogram("deltaPT_mu_addtau", "abs(boosted_pt_1-boosted_pt_add)", np.arange(0, 20, 0.5)),
}   

control_binning = {}
for channel in ["et", "mt", "tt"]:
    control_binning[channel] = common_binning
